# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

workspace 'Juke'
use_frameworks!

def all_pods
    pod 'NVActivityIndicatorView'
    pod 'Alamofire', '~> 4.5'
    pod 'AlamofireImage', '~> 3.1'
    pod 'Unbox'
    pod 'PKHUD', :git => 'https://github.com/pkluz/PKHUD.git', :branch => 'release/swift4'
    pod 'ESTMusicIndicator'
    pod 'SCLAlertView'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'FirebaseUI/Database', '~> 4.0'
    pod 'Whisper', '5.1.0'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    pod 'XLActionController'
    pod 'Fabric', '~> 1.7.2'
    pod 'Crashlytics', '~>  3.9.3'
    pod 'XLPagerTabStrip'
    pod 'Presentr'
    pod 'SkyFloatingLabelTextField', '~> 3.0'
end

target 'Juke Production' do
  all_pods
end

target 'Juke Dev' do
    all_pods
end
