# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Juke' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Juke
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'
    pod 'Unbox'
    pod 'PKHUD', '~> 4.0'
    pod 'ESTMusicIndicator'
    pod 'SCLAlertView'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'
    pod 'Firebase/Storage'
    pod 'Firebase/Messaging'
    pod 'FirebaseUI/Database', '~> 4.0'
    pod 'Whisper'
    pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
    pod 'XLActionController'

end
